import { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-macbook",
    name: "2020 Apple MacBook Pro with Apple M1 Chip (13-inch, 8GB RAM, 256GB SSD Storage) - Space Gray",
    description: "Experience the ultimate productivity machine. Powered by the revolutionary M1 chip, this MacBook Pro delivers incredible performance and battery life.",
    price: 1699.00,
    originalPrice: 1999.00,
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1000&auto=format&fit=crop",
    thumbnails: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1531297172864-459194bb8bd2?q=80&w=400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1527443154391-507e9dc6c5cc?q=80&w=400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1537498425277-c283d32ef9db?q=80&w=400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=400&auto=format&fit=crop"
    ],
    category: "Electronics Devices",
    stock: 5,
    vendorId: "vendor-apple",
    rating: 4.7,
    sku: "A264671",
    brand: "Apple",
    colors: [
      { name: "Space Gray", hex: "#7d7e80" },
      { name: "Silver", hex: "#e3e4e5" }
    ],
    sizes: ["14-inch Liquid Retina XDR display", "16-inch Liquid Retina XDR display"],
    memoryOptions: ["16GB unified memory", "32GB unified memory", "64GB unified memory"],
    storageOptions: ["1TV SSD Storage", "2TV SSD Storage", "4TV SSD Storage", "8TV SSD Storage"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      "Free 1 Year Warranty",
      "Free Shipping & Fasted Delivery",
      "100% Money-back guarantee",
      "24/7 Customer support",
      "Secure payment method"
    ],
    shippingInfo: [
      { label: "Courier", value: "2 - 4 days, free shipping" },
      { label: "Local Shipping", value: "up to one week, $19.00" },
      { label: "UPS Ground Shipping", value: "4 - 6 days, $29.00" },
      { label: "Unishop Global Export", value: "3 - 4 days, $39.00" }
    ],
    specification: [
      { label: "Brand", value: "Apple" },
      { label: "Model", value: "MacBook Pro 2020" },
      { label: "Processor", value: "Apple M1 Chip" },
      { label: "RAM", value: "8GB" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Screen", value: "13.3-inch Retina display" },
      { label: "Color", value: "Space Gray" }
    ]
  },
  {
    id: "prod-1",
    name: "Active Smart Watch",
    description: "Feature-packed smartwatch tracking health, activities, and notifications with style.",
    price: 29.90,
    imageUrl: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=400&auto=format&fit=crop",
    category: "Electronics & Gadgets",
    stock: 15,
    vendorId: "vendor-b",
    rating: 5.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-2",
    name: "Premium Wireless Headset",
    description: "Active noise cancellation, 40hr battery runtime, comfortable leather cushions.",
    price: 29.90,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=400&auto=format&fit=crop",
    category: "Electronics & Gadgets",
    stock: 12,
    vendorId: "vendor-a",
    rating: 5.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-3",
    name: "Retro Classic Camera",
    description: "Capture beautiful moments with manual controls and iconic vintage aesthetics.",
    price: 29.90,
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=400&auto=format&fit=crop",
    category: "Electronics & Gadgets",
    stock: 7,
    vendorId: "vendor-c",
    rating: 5.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-4",
    name: "Classic Minimalist Watch",
    description: "Elegant stainless steel case with premium brown leather strap design.",
    price: 145.00,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=400&auto=format&fit=crop",
    category: "Fashion & Apparel",
    stock: 8,
    vendorId: "vendor-b",
    rating: 4.6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-5",
    name: "Premium Leather Wallet",
    description: "Slim bifold layout crafted from full-grain vegetable-tanned leather.",
    price: 29.90,
    imageUrl: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?q=80&w=400&auto=format&fit=crop",
    category: "Fashion & Apparel",
    stock: 20,
    vendorId: "vendor-a",
    rating: 4.7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-6",
    name: "Insulated Thermal Bottle",
    description: "Double-walled vacuum insulation keeps hot drinks hot and cold drinks ice-cold.",
    price: 29.99,
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?q=80&w=400&auto=format&fit=crop",
    category: "Home & Living",
    stock: 45,
    vendorId: "vendor-a",
    rating: 4.9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-7",
    name: "Organic Matcha Powder",
    description: "Premium ceremonial grade green tea powder stoneground from Japan.",
    price: 29.90,
    imageUrl: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?q=80&w=400&auto=format&fit=crop",
    category: "Food & Beverages",
    stock: 30,
    vendorId: "vendor-d",
    rating: 5.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-8",
    name: "Gourmet Coffee Beans",
    description: "Single-origin medium roast Arabica coffee beans with rich chocolate notes.",
    price: 19.99,
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=400&auto=format&fit=crop",
    category: "Food & Beverages",
    stock: 50,
    vendorId: "vendor-d",
    rating: 4.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-9",
    name: "Smart Fitness Tracker",
    description: "Waterproof health band tracking heart rate, sleep cycles, and daily steps.",
    price: 79.99,
    imageUrl: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?q=80&w=400&auto=format&fit=crop",
    category: "Health & Wellness",
    stock: 25,
    vendorId: "vendor-e",
    rating: 4.5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-10",
    name: "Aromatherapy Oil Diffuser",
    description: "Ultrasonic cool mist humidifier with 7 LED color light options and quiet operation.",
    price: 29.90,
    imageUrl: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?q=80&w=400&auto=format&fit=crop",
    category: "Health & Wellness",
    stock: 40,
    vendorId: "vendor-c",
    rating: 4.7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-11",
    name: "Bluetooth Speaker",
    description: "Portable wireless speaker with rich bass, 360-degree sound, and waterproof design.",
    price: 49.99,
    imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=400&auto=format&fit=crop",
    category: "Electronics & Gadgets",
    stock: 18,
    vendorId: "vendor-b",
    rating: 4.6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-12",
    name: "Gaming Keyboard",
    description: "Mechanical key switches, customizable RGB backlighting, and dedicated media keys.",
    price: 89.90,
    imageUrl: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=400&auto=format&fit=crop",
    category: "Electronics & Gadgets",
    stock: 10,
    vendorId: "vendor-a",
    rating: 4.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-13",
    name: "Unisex Cotton Hoodie",
    description: "Ultra-soft cotton blend hoodie with front pouch pocket and adjustable drawstring.",
    price: 39.50,
    imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=400&auto=format&fit=crop",
    category: "Fashion & Apparel",
    stock: 22,
    vendorId: "vendor-c",
    rating: 4.5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-14",
    name: "Canvas Sneakers",
    description: "Classic low-top lace-up sneakers crafted from durable breathable canvas.",
    price: 45.00,
    imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=400&auto=format&fit=crop",
    category: "Fashion & Apparel",
    stock: 15,
    vendorId: "vendor-b",
    rating: 4.4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-15",
    name: "Leather Backpack",
    description: "Handcrafted top-grain leather backpack with padded laptop sleeve compartment.",
    price: 120.00,
    imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=400&auto=format&fit=crop",
    category: "Fashion & Apparel",
    stock: 6,
    vendorId: "vendor-a",
    rating: 4.9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-16",
    name: "Ceramic Mug Set",
    description: "Set of 4 matte finish ceramic coffee mugs with comfortable ergonomic handles.",
    price: 24.99,
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=400&auto=format&fit=crop",
    category: "Home & Living",
    stock: 14,
    vendorId: "vendor-d",
    rating: 4.7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-17",
    name: "Cotton Throw Blanket",
    description: "Lightweight and breathable handwoven cotton throw, perfect for beds and couches.",
    price: 34.90,
    imageUrl: "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?q=80&w=400&auto=format&fit=crop",
    category: "Home & Living",
    stock: 18,
    vendorId: "vendor-b",
    rating: 4.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-18",
    name: "Soy Wax Candle",
    description: "Slow-burning soy candle infused with natural lavender and vanilla essential oils.",
    price: 15.99,
    imageUrl: "https://images.unsplash.com/photo-1603006905003-be475563bc59?q=80&w=400&auto=format&fit=crop",
    category: "Home & Living",
    stock: 35,
    vendorId: "vendor-c",
    rating: 4.6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-19",
    name: "Modern Desk Organizer",
    description: "Sturdy wooden desktop organizer tray with compartments for files and stationary.",
    price: 19.90,
    imageUrl: "https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?q=80&w=400&auto=format&fit=crop",
    category: "Home & Living",
    stock: 20,
    vendorId: "vendor-a",
    rating: 4.5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-20",
    name: "Raw Organic Honey",
    description: "Pure wildflower honey gathered sustainably from local apiaries, uncooked.",
    price: 14.50,
    imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=400&auto=format&fit=crop",
    category: "Food & Beverages",
    stock: 25,
    vendorId: "vendor-d",
    rating: 4.9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-21",
    name: "Dark Chocolate Bar",
    description: "Single-origin 72% dark chocolate with notes of wild berries and coffee beans.",
    price: 7.99,
    imageUrl: "https://images.unsplash.com/photo-1601924638867-3a6de6b7a500?q=80&w=400&auto=format&fit=crop",
    category: "Food & Beverages",
    stock: 60,
    vendorId: "vendor-e",
    rating: 4.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-22",
    name: "Herbal Tea Sampler",
    description: "Variety pack of 12 distinct caffeine-free herbal tea blends in biodegradable sachets.",
    price: 22.00,
    imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=400&auto=format&fit=crop",
    category: "Food & Beverages",
    stock: 40,
    vendorId: "vendor-d",
    rating: 4.7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-23",
    name: "Sunscreen SPF 50",
    description: "Broad-spectrum mineral sunscreen formulated with zinc oxide and organic aloe.",
    price: 18.90,
    imageUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=400&auto=format&fit=crop",
    category: "Health & Wellness",
    stock: 30,
    vendorId: "vendor-e",
    rating: 4.6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-24",
    name: "Eco Yoga Mat",
    description: "Non-slip alignment yoga mat made from biodegradable natural tree rubber material.",
    price: 35.00,
    imageUrl: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?q=80&w=400&auto=format&fit=crop",
    category: "Health & Wellness",
    stock: 15,
    vendorId: "vendor-c",
    rating: 4.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-25",
    name: "Vitamin C Serum",
    description: "Highly stable antioxidant facial serum designed to brighten skin and reduce fine lines.",
    price: 24.99,
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=400&auto=format&fit=crop",
    category: "Health & Wellness",
    stock: 20,
    vendorId: "vendor-a",
    rating: 4.7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-26",
    name: "PlayStation 5 Console",
    description: "Experience lightning-fast loading with an ultra-high speed SSD and immersive 3D Audio.",
    price: 499.99,
    imageUrl: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?q=80&w=400&auto=format&fit=crop",
    category: "Electronics & Gadgets",
    stock: 5,
    vendorId: "vendor-b",
    rating: 5.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-27",
    name: "Smart Voice Assistant Speaker",
    description: "Voice control your music, smart home devices, and get hands-free helper functions.",
    price: 49.90,
    imageUrl: "https://images.unsplash.com/photo-1543512214-318c7553f230?q=80&w=400&auto=format&fit=crop",
    category: "Electronics & Gadgets",
    stock: 12,
    vendorId: "vendor-a",
    rating: 5.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-28",
    name: "Next-Gen Foldable Smartphone",
    description: "Experience the future with a seamless folding display and pro-grade cameras.",
    price: 1299.99,
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351cb315?q=80&w=400&auto=format&fit=crop",
    category: "New Arrival",
    stock: 10,
    vendorId: "vendor-f",
    rating: 4.9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-29",
    name: "Ultralight Running Shoes",
    description: "Breathable mesh upper with highly responsive foam cushioning for everyday runs.",
    price: 110.00,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=400&auto=format&fit=crop",
    category: "New Arrival",
    stock: 25,
    vendorId: "vendor-g",
    rating: 4.7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-30",
    name: "Ergonomic Office Chair",
    description: "Adjustable lumbar support and breathable mesh back for all-day comfort.",
    price: 249.00,
    imageUrl: "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?q=80&w=400&auto=format&fit=crop",
    category: "Best Seller",
    stock: 50,
    vendorId: "vendor-h",
    rating: 4.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-31",
    name: "Noise-Cancelling Earbuds",
    description: "True wireless earbuds with active noise cancellation and spatial audio.",
    price: 149.99,
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=400&auto=format&fit=crop",
    category: "Best Seller",
    stock: 120,
    vendorId: "vendor-i",
    rating: 4.9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-32",
    name: "Luxury Mall Gift Card",
    description: "A premium gift card redeemable at over 50 exclusive mall boutiques.",
    price: 100.00,
    imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=400&auto=format&fit=crop",
    category: "Malls",
    stock: 500,
    vendorId: "vendor-j",
    rating: 5.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-33",
    name: "Designer Sunglasses Collection",
    description: "Exclusive aviator style sunglasses available only at our partner malls.",
    price: 185.50,
    imageUrl: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=400&auto=format&fit=crop",
    category: "Malls",
    stock: 15,
    vendorId: "vendor-k",
    rating: 4.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
